#Utility Configuration
#Fri Mar 06 18:38:26 CET 2026
audioDevice=CABLE Output (VB-Audio Virtual Cable)
castKey=33
fishCaught=4972
interactKey=11
logoutAfterFullBag=true
logoutKey=4
longBreakDurationMax=3
longBreakDurationMin=2
longBreakIntervalMax=350
longBreakIntervalMin=300
lureEnabled=true
lureInterval=10
lureKey=34
reactionTime=350
roiH=259
roiW=280
roiX=798
roiY=192
runTimeLimit=182
screenIndex=1
shortBreakDurationMax=120
shortBreakDurationMin=30
shortBreakIntervalMax=120
shortBreakIntervalMin=60
showDetectionPoint=false
splashThreshold=2.0
throws=17952
